Attempt to fix crash when a song is removed from queue
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!
      Expected adapter item count: 2243, found: 2242
      Pager id: com.poupa.vinylmusicplayer.ci:id/player_album_cover_viewpager
      Pager class: class androidx.viewpager.widget.ViewPager
      Problematic adapter: class com.poupa.vinylmusicplayer.adapter.AlbumCoverPagerAdapter
            at androidx.viewpager.widget.ViewPager.populate(Unknown Source:569)
            at androidx.viewpager.widget.ViewPager.populate(Unknown Source:2)
            at androidx.viewpager.widget.ViewPager$3.run(Unknown Source:8)